### ISSUE TITLE
How well does this crate handle invalid input?

### ISSUE THREAD

**Issue by emilio** [bodoni/truetype#5]
Hi, so @vvuk has PR'd Windows support for webfonts in Servo https://github.com/servo/servo/pull/15096#issuecomment-273577198, for what it uses your crate.

I was just wondering how well does this crate handle invalid input, because we may need to reconsider it if it can't handle it properly (given Servo would be feeding it random network data).

I've taken a quick look at the code and it seems reasonable, but I'm totally not an expert in fonts, so I wonder if you could help me figure out whether all the usages of `unsafe` are sound here.

Thanks for the answers!

**Comment by IvanUkhov** [comment]
Thanks for the issue! If you’re talking about malformed font files, the crate strictly follows the spec, and everything that is invalid is rejected as soon as the problem is detected; there’s no attempt to continue parsing. Regarding the `unsafe` blocks, in principle, they can go. I was just trying to make the code more efficient. Any ideas and suggestions are welcome!

**Comment by emilio** [comment]
Sounds ok to me, thank for the reply!

Yeah, I meant malformed fonts and similar, and I don't have a better idea from the unsafe stuff (as far as I understand it is only for transmuting between differently-sized types that are interpreted as plain data and validated afterwards), so I'm closing this for now.

Thanks again for replying!
