### ISSUE TITLE
Ignoring unsupported sub-tables

### ISSUE THREAD

**Issue by SimonSapin** [bodoni/truetype#8]
Hi. In the first font I tried, accessing `CharMapping` failed with:

```
thread 'main' panicked at 'not yet implemented', /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/truetype-0.26.2/src/char_mapping.rs:109:21
```

It looks like this is because `CharMapping::read` tries does parse every `Record` but only supports a couple formats. If the font contains any in an unsupported format, `unimplemented!()` is called before parsing finishes. Maybe this font has *some* cmap records in a format that’s supported, and accessing those might be enough.

I’m not sure what a better API would be though. What do you think?

**Comment by IvanUkhov** [comment]
Thank you for the issue! I suppose it’s related to #6.

Yes, it definitely makes sense to ignore unsupported encodings, as there might be many, and one of them might be supported and enough. I think one could introduce `Unsupported` to `char_mapping::Encoding` and then push it to `encodings` instead of `unimplemented!()`. It shouldn’t affect the subsequent reading, as there is a jump at the beginning of each iteration. Not pushing anything is not an option, as `records` and `encodings` should be kept in sync.

**Comment by IvanUkhov** [comment]
Do you have an example of a typeface that has this problem and that is licensed under something like OFL so that it could be used for testing?

**Comment by SimonSapin** [comment]
This is Vera Sans from https://www.gnome.org/fonts/. It has a custom license “considered to be similar in terms to the Apache License 2.0” by ASF: https://www.apache.org/legal/resolved.html#category-a

**Comment by IvanUkhov** [comment]
Thanks! I’ll have a look at it.

**Comment by IvanUkhov** [comment]
Fixed.
